name: "Better Subtitle Extractor"
guid: "77BE2143-68BE-4E77-AFC8-82859969038A"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-extractsubs.png"
version: 7
targetAbi: "12.0.0.0"
framework: "net10.0"
owner: "jellyfin"
overview: "Extracts Subtitles."
description: >
  Extracts embedded subtitles.

category: "Subtitles"
artifacts:
  - "Jellyfin.Plugin.SubtitleExtract.dll"
changelog: |-
  - Fix HasChanged checks (#57) @Shadowghost
